config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "records#index"
  resources :records do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: :show do
    get :favorites, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bodypart.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '顔' },
    { id: 2, name: '頭' },
    { id: 3, name: '耳' },
    { id: 4, name: '胸' },
    { id: 5, name: '腹部' },
    { id: 6, name: '背中' },
    { id: 7, name: '腕' },
    { id: 8, name: '手' },
    { id: 9, name: '足' },
    { id: 10, name: '上肢' },
    { id: 11, name: '下肢' },
    { id: 12, name: '脇' },
    { id: 13, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :records

  end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :record
  belongs_to :user

  validates :text, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :record

  validates_uniqueness_of :record_id, scope: :user_id
end

app/models/record.rb
class Record < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :bodypart
  belongs_to :symptom
  has_many_attached :images
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :images, :onset_date, :bodypart_id, :symptom_id, presence: true
  validates :images, length: { minimum: 1, maximum: 3, message: 'は1枚以上3枚以下にしてください' }
  validates :onset_time, presence: true,
                         numericality: { only_integer: true, message: 'は半角数字で入力してください' },
                         inclusion: { in: 0..23, message: 'は0〜23で入力してください' }

  def self.search(search)
    if search != ""
      Record.where('bodypart LIKE(?) OR symptom LIKE(?) OR diagnosis LIKE(?) OR cause LIKE(?) OR prescription_drug LIKE(?) OR memo LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      Record.all
    end
  end

  def favorited?(user)
    favorites.where(user_id: user.id).exists?
 end
end

app/models/symptom.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: 'かゆみ' },
    { id: 2, name: '痛み' },
    { id: 3, name: 'ぶつぶつ' },
    { id: 4, name: '赤み' },
    { id: 5, name: 'カサカサ' },
    { id: 6, name: 'にきび' },
    { id: 7, name: 'じんましん' },
    { id: 8, name: 'アトピー' },
    { id: 9, name: 'イボ' },
    { id: 10, name: 'タコ・ウオノメ' },
    { id: 11, name: '腫れ' },
    { id: 12, name: '水ぶくれ' },
    { id: 13, name: '虫刺され' },
    { id: 14, name: '水虫' },
    { id: 15, name: 'やけど' },
    { id: 16, name: '脱毛' },
    { id: 17, name: 'しこり' },
    { id: 18, name: 'あざ' },
    { id: 19, name: 'ほくろ' },
    { id: 20, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :records

  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :records, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :nickname, presence: true
  validates :password, length: { minimum: 8, message: 'は6文字以上で入力してください' },
            format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は半角英数字で入力してください' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/records/#{comment.record.id}"
  end

  def destroy
    @record = Record.find(params[:id])
    @comment = Comment.find(params[:record_id])
    if @comment.destroy
      redirect_to record_path(@record.id)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, record_id: params[:record_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @record_favorite = Favorite.new(user_id: current_user.id, record_id: params[:record_id])
    @record_favorite.save
    redirect_to record_path(params[:record_id]) 
  end
  
  def destroy
    @record_favorite = Favorite.find_by(user_id: current_user.id, record_id: params[:record_id])
    @record_favorite.destroy
    redirect_to record_path(params[:record_id]) 
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  def index
    @records = Record.includes(:user).order('created_at DESC')
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(record_params)
    if @record.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @record.comments.includes(:user)
  end

  def edit
    redirect_to root_path if current_user.id != @record.user_id
  end

  def update
    if @record.update(record_params)
      redirect_to record_path(@record.id)
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == @record.user_id
      @record.destroy
      redirect_to root_path
    end
  end

  def search
    @records = Record.search(params[:keyword])
  end

  private

  def record_params
    params.require(:record).permit(:onset_date, :onset_time, :bodypart_id, :symptom_id, :visit_date, :hospital_name, :diagnosis,
                                   :cause, :prescription_drug, :remission_date, :memo, { images: [] }).merge(user_id: current_user.id)
  end

  def set_record
    @record = Record.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @nickname = @user.nickname
    @records = @user.records.order('created_at DESC')

    favorites = Favorite.where(user_id: current_user.id).pluck(:record_id)
    @favorite_list = Record.find(favorites) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite.html.erb
<% if !Favorite.exists?(user_id: current_user.id, record_id: @record.id) %>
  <%= link_to record_favorites_path(@record.id), method: :post, remote: true, class:"like-btn" do %>
    <span class="record__btn">保存</span>
  <% end %>
  <span class="star-count1"><%= @record.favorites.count %></span>
<% else %>
  <%= link_to record_favorite_path(@record.id, id: @record.favorites[0].id), method: :delete, remote: true, class:"like-btn" do %>
    <span class="record__btn">保存</span>
  <% end %>
  <span class="star-count2"><%= @record.favorites.count %></span>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_<%= @record.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { record: @record }) %>");

app/views/favorites/destroy.js.erb
$('#favorite_<%= @record.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { record: @record }) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>HifuNote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class='search-bar-contents'>
            <%= link_to image_tag("hifunote_logo_grey.png", class: :logo), root_path %>
            <%= form_with(url: search_records_path, local: true, method: :get, class: "search-form") do |form| %>
              <%= form.text_field :keyword, placeholder: 'キーワードから探す', class: 'input-box' %>
              <%= form.submit "検索", class: "search-btn" %>
            <% end %>
          </div>
            <% if user_signed_in? %>
              <div class="nav__right">
                <%= link_to "マイページ", user_path(current_user.id), class: :nav__btn %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__btn %>
              </div> 
            <% else %>
              <div class="nav__right">
                <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
                <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
              </div>
            <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © HifuNote All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/records/_form.html.erb
<%= form_with model: @record, id: 'new_record', local: true do |form| %>

    <%= render 'shared/error_messages', model: form.object %>

      <div class="field">
        <%= form.label :image, "症状の画像" %><br />
        <div id="previews"></div>
        <div class="click-upload">
          <%= form.file_field :images, name: 'record[images][]', data: {index: 0}, id:"record_image" %>
        </div>
      </div>

      <div class="field">
        <%= form.label :onset_date, "発症日" %><br />
        <%= form.date_field :onset_date, id:"record_onset_date" %>
      </div>

      <div class="field">
        <%= form.label :onset_time, "発症した時刻" %><br />
        <%= form.number_field :onset_time, in: 0..23, id:"record_onset_time" %>時頃
      </div>

      <div class="field">
        <%= form.label :bodypart, "発症した部位" %><br />
        <%= form.text_field :bodypart, id:"record_bodypart" %>
      </div>

      <div class="field">
        <%= form.label :symptom, "症状" %><br />
        <%= form.text_field :symptom, id:"record_symptom" %>
      </div>

      <div class="field">
        <%= form.label :visit_date, "病院へ行った日" %><br />
        <%= form.date_field :visit_date, id:"record_visit_date" %>
      </div>

      <div class="field">
        <%= form.label :hospital_name, "病院名" %><br />
        <%= form.text_field :hospital_name, id:"record_hospital_name" %>
      </div>

      <div class="field">
        <%= form.label :diagnosis, "診断された病名" %><br />
        <%= form.text_field :diagnosis, id:"record_diagnosis" %>
      </div>

      <div class="field">
        <%= form.label :cause, "診断された原因" %><br />
        <%= form.text_field :cause, id:"record_cause" %>
      </div>

      <div class="field">
        <%= form.label :prescription_drug, "処方された薬" %><br />
        <%= form.text_field :prescription_drug, id:"record_prescription_drug" %>
      </div>

      <div class="field">
        <%= form.label :remission_date, "寛解日" %><br />
        <%= form.date_field :remission_date, id:"record_remission_date" %>
      </div>

      <div class="field">
        <%= form.label :memo, "メモ" %><br />
        <%= form.text_area :memo, class: :form__text, id:"record_memo" %>
      </div>

      <%= form.submit "保存する", class: :form__btn %>
<% end %>

app/views/records/_record.html.erb
<div class="card">
  <%= link_to image_tag(record.images[0], class: :card__img), record_path(record.id) %>
  <div class="card__body">
    <p class="card__summary">
      <%= record.bodypart %>
    </p>
    <%= link_to "by #{record.user.nickname}", user_path(record.user_id), class: :card__user %>
  </div>
</div>

app/views/records/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">編集する</h2>
        <%= render partial: "form" %>
         <%= link_to 'もどる', record_path(@record.id), class: :form__btn %>
    </div>
  </div>
</div>

app/views/records/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、<a href="/users/<%= current_user.id %>" class="greeting__link"><%= current_user.nickname %>さん</a>
      </div>
    <% end %>
    <%# HifuNoteとは %>
    <div class='feature-contents'>
      <h2 class='title'>
        皮膚症状記録アプリ -HifuNote-
      </h2>
      <ul class='feature-lists'>
        <li class='list'>
          <%= image_tag "hifunote-intro01.png", class:"list-pict" %>
          <h3 class='feature-list-text'>
            症状が出たらすぐに記録できる！
          </h3>
          <p class='feature-list-description'>
            スマホで写真を撮って、発症日時や症状と一緒に記録することができます
          </p>
        </li>
        <li class='list'>
          <%= image_tag "hifunote-intro02.png", class:"list-pict" %>
          <h3 class='feature-list-text'>
            病院で記録を見ながら説明できる！
          </h3>
          <p class='feature-list-description'>
            写真を見せたり、記録した情報を見ながらきちんと症状を説明することできます
          </p>
        </li>
        <li class='list'>
          <%= image_tag "hifunote-intro03.png", class:"list-pict" %>
          <h3 class='feature-list-text'>
            他のユーザーと記録を共有できる！
          </h3>
          <p class='feature-list-description'>
            部位、症状ごとの一覧記録から似たような症状を見つけることができます
          </p>
        </li>
      </ul>
    </div>

    <%# スマホアプリリンク %>
    <div class='ad-contents'>
      <h2 class='ad-title'>
        スマホアプリをダウンロード
      </h2>
      <div class='store-btn'>
        <%= link_to image_tag("smartphone.png", class:"smartphone-img") %>
        <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
        <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
      </div>
    </div>

    <%# 最新投稿 %>
    <h2 class='index-list'>最近投稿された症状記録</h2>
    <div class="card__wrapper">
      <%= render partial: "record", collection: @records %>
    </div>
  </div>
</main>

<%= link_to(new_record_path, class: 'record-btn') do %>
  <span class='record-btn-text'>記録する</span>
  <%= image_tag 'icon_pencil.png', size: '185x50', class: "record-btn-icon" %>
<% end %>

app/views/records/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">登録する</h2>
        <%= render partial: "form" %>
    </div>
  </div>
</div>

app/views/records/search.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        検索結果一覧
      </h2>
      <div class="user__card">
        <% @records.each do |tweet| %>
          <%= render partial: "record", collection: @records %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/records/show.html.erb
<div class="record-show">
  <div class="record-box">
    <div class="record-img-content">
      <%= image_tag @record.images[0], class: "main-image" %><br>
        <% @record.images[1..-1].each do |image| %>
          <div class="other-images">
            <%= image_tag image, class: "main-image" %>
          </div>
        <%end%>
    </div>

    <% if user_signed_in? && current_user.id == @record.user_id %>
      <div class="record__manage">
        <%= link_to "編集", edit_record_path(@record.id), method: :get, class: :record__btn %>
        <%= link_to "削除", record_path(@record.id), method: :delete, class: :record__btn %>
      </div>
    <% end %>

    <% if user_signed_in? && current_user.id != @record.user_id %>
      <% if @record.favorited?(current_user) %>
        <%= link_to record_favorite_path(@record.id), method: :delete do %>
        <span class="record__btn favorite">保存済</span>
        <% end %>
      <% else %>
        <%= link_to record_favorites_path(@record.id), method: :post do %>
        <span class="record__btn">保存</span>
        <% end %>
      <% end %>
    <% end %>

    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-record">投稿者</th>
          <td class="detail-value"><a href="/users/<%= @record.user.id %>"><%= @record.user.nickname %></a></td>
        </tr>
        <tr>
          <th class="detail-record">発症日時</th>
          <td class="detail-value"><%= @record.onset_date %> / <%= @record.onset_time %>時頃</td>
        </tr>
        <tr>
          <th class="detail-record">発症部位</th>
          <td class="detail-value"><%= @record.bodypart %></td>
        </tr>
        <tr>
          <th class="detail-record">症状</th>
          <td class="detail-value"><%= @record.symptom %></td>
        </tr>
        <tr>
          <th class="detail-record">病院へ行った日</th>
          <td class="detail-value"><%= @record.visit_date %></td>
        </tr>
        <% if user_signed_in? && current_user.id == @record.user_id %>
          <tr>
            <th class="detail-record">病院名</th>
            <td class="detail-value"><%= @record.hospital_name %></td>
          </tr>
        <% end %>
        <tr>
          <th class="detail-record">診断された病名</th>
          <td class="detail-value"><%= @record.diagnosis %></td>
        </tr>
        <tr>
          <th class="detail-record">診断された原因</th>
          <td class="detail-value"><%= @record.cause %></td>
        </tr>
        <tr>
          <th class="detail-record">処方された薬</th>
          <td class="detail-value"><%= @record.prescription_drug %></td>
        </tr>
        <tr>
          <th class="detail-record">寛解日</th>
          <td class="detail-value"><%= @record.remission_date %></td>
        </tr>
        <tr>
          <th class="detail-record">メモ</th>
          <td class="detail-value"><%= @record.memo %></td>
        </tr>
      </tbody>
    </table>
    <%# コメント欄 %>
    <div class="record__comments">
      <% if user_signed_in? %>
        <%= form_with(model: [@record, @comment], local: true) do |form| %>
          <div class="field">
            <%= form.label :text, "コメント" %><br />
            <%= form.text_area :text, class: :comment_content %>
          </div>
          <div class="actions">
            <%= form.submit "送信する", class: :form__btn %>
          </div>
        <% end %>
      <% else %>
        <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
      <% end %>
      <ul class="comments_lists">
        <% @comments.each do |comment| %>
          <li class="comments_list">
            <p>
              <%= comment.text %>
              <%= link_to "[#{comment.user.nickname}]", "/users/#{comment.user_id}", class: :comment_user %>
              <%= l comment.created_at %>
              <% if current_user.id == comment.user_id %>
                <%= link_to "削除", record_comment_path(comment.id), method: :delete, class: :comment_btn %>
              <% end %>
            </p>
          </li>
        <% end %>
      </ul>
    </div>
    <%# /コメント欄 %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= @nickname %>さんの投稿一覧
      </h2>
      <div class="user__card">
        <% @records.each do |record| %>
          <div class="card">
            <%= link_to image_tag(record.images[0], class: :card__img), record_path(record.id) %>
            <div class="card__body">
              <p class="card__summary">
                <%= record.bodypart %>
              </p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="user__wrapper">
      <% if @favorite_list.present? %>
        <h2 class="page-heading">
          <%= @nickname %>さんの保存一覧
        </h2>
        <div class="user__card">
          <% @favorite_list.each do |record| %>
            <div class="card">
              <%= link_to image_tag(record.images[0], class: :card__img), record_path(record.id) %>
              <div class="card__body">
                <p class="card__summary">
                  <%= link_to "by #{record.user.nickname}", user_path(record.user_id), class: :card__user %>
                </p>
              </div>
            </div>
          <% end %>
        </div>
      <% end%>
    </div>
  </div>
</div>